stages:
  - test

test:
  image: python:3.8.6
  stage: test
  tags:
    - docker
  script:
    - pip install -r requirements.txt
    - cd vilosky_paths
    - python manage.py makemigrations
    - python manage.py migrate --run-syncdb
    - python manage.py test
